name: vHive unit tests

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  workflow_dispatch:

env:
  GOOS: linux
  GO111MODULE: on

jobs:
  timeseriesdb_test:
    name: TimeseriesDB Tests
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: tools/timeseriesdb
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run tests
        run: go test -v -race -cover ./...
